# configs/base_experiment.yaml

# --- Experiment Setup ---
experiment_setup:
  experiment_name: "base_experiment"
  seed: 21
  device: "cuda"
  TQDM_NCOLS: 100

# --- Model Configuration ---
model:
  type: "efficientnet_b0"
  # pretrained: True
  # force_reload_hub: False

# --- Training Loop Parameters ---
training:
  num_epochs: 20
  batch_size: 64
  optimizer:
    type: "AdamW"
    lr: 0.0003
    weight_decay: 0.0001
  scheduler:
    type: "CosineAnnealingLR"
    t_max: 20
    min_lr: 0.0
  amp_enabled: True
  accum_steps: 2
  val_interval: 1
  model_selection_metric: "mean_optimal_sensitivity"
  save_optimal_thresholds: True
  early_stopping_patience: 10
  ema_decay: 0.999
  use_ema_for_val: True
  freeze_epochs: 0
  backbone_lr_mult: 0.1

  loss:
    type: "ldam_loss"
    ldam_max_margin: 0.5
    ldam_use_effective_number_margin: True
    ldam_effective_number_beta: 0.999

  drw_schedule_epochs: [30, 40]
  pauc_max_fpr: 0.2

# --- Data Handling & Augmentations ---
data:
  num_workers: 8
  prefetch_factor: 4
  sampler:
    type: "default"       # Options: "default", "class_balanced_sqrt"

  cpu_augmentations:
    resize: 256
    crop_size: 224
    norm_mean: [0.485, 0.456, 0.406]
    norm_std: [0.229, 0.224, 0.225]
    train:
      random_horizontal_flip_p: 0.5
      random_vertical_flip_p: 0.0
      affine_degrees: 15
      affine_translate: [0.05, 0.05]
      affine_scale_range: [0.9, 1.1]
      affine_shear_degrees: 10
      color_jitter_brightness: 0.1
      color_jitter_contrast: 0.1
      color_jitter_saturation: 0.1
      color_jitter_hue: 0.1
      rand_aug_n: 2
      rand_aug_m: 9

  gpu_augmentations:
    enable: False
    pipeline: []

# --- Paths Configuration ---
paths:
  labels_csv: "../splits/training/labels.csv"
  train_root: "../splits/training"
  log_dir: "../outputs/tensorboard"
  ckpt_dir: "../outputs/checkpoints"

# --- PyTorch Compile (optional) ---
torch_compile:
  enable: False
  mode: "default"

# --- TensorBoard Logging ---
tensorboard_logging:
  enable: True
  log_interval_batches_train: 50
  log_interval_batches_val: 10
  log_epoch_summary: True
  log_lr: True
  log_throughput: True
  log_gpu_time_epoch: True

  image_logging:
    enable: False
    num_samples: 4
    denormalize: True
    log_at_epochs: [0, 25, 49]
    log_train_input: True
    log_val_input: True

  profiler:
    enable: False
    profile_epoch: 1
    wait_steps: 5
    warmup_steps: 5
    active_steps: 10
    repeat_cycles: 0
    record_shapes: True
    profile_memory: True
    with_stack: True
    sort_by: "self_cuda_time_total"
    row_limit: 20
    export_chrome_trace_manual: False

  memory_logging:
    enable: True
    log_interval_batches: 100
    log_epoch_summary: True
